const express = require('express');
const mongoose = require('mongoose');
const morgan = require('morgan');
const app = express();
app.use(express.json());
app.use(morgan('tiny'));
const PORT = 4001;
const MONGO_URL = process.env.MONGO_URL || 'mongodb://localhost:27017/users';
mongoose.connect(MONGO_URL).then(() => console.log('User MongoDB connected')).catch(console.error);
app.get('/api/v1/health', (req, res) => res.json({ status: 'ok', service: 'user' }));
app.use('/api/v1', require('./routes/auth'));
app.use('/api/v1', require('./routes/user'));
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: err.message }); });
app.listen(PORT, () => console.log(`User service listening on ${PORT}`));
